name: iOS Build

on:
  pull_request:
    branches: 
      - master
  workflow_dispatch:

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          lfs: true

      # Cache
      - uses: actions/cache@main
        with:
          path: Library
          key: Library

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v2.0-alpha-6
        with:
          unityVersion: 2020.2.3f1
          targetPlatform: iOS
